### ISSUE TITLE
New email template

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#232]
### What would you like?

Receive the email in the new template.

I'd like to propose to update the mailing template for confirmations to be as follows (generate HTML [here](https://stijl.gewis.nl/mailings-demo)):

```yaml
# Registration confirmation
---
# All mailings require some settings. These can be set here. Don't forget to set the title ("Algemene mededeling; tekst zelf invoeren")
version: 1.1
settings:
    title: "Registration Confirmation GEWIS"
    email: "secr@gewis.nl"
    lang: en-UK
    #lang: nl-NL
    follow: true

# A mailing consists of a series of messageblocks, each with their own type
# The available types are "header", "topblock", "activities", "activityfooter", "extramessage" and "tinyfooter"
messageblocks:

# Each mailing must have a header to make the template shine! It contains the title and the date.
    - type: "header"
      title: "Update on your registration"
      date: 2022-10-26

# This is the first block which is shown on top of the message. Recommended for most messages
    - type: topblock
      title: "You have been confirmed as member of GEWIS!*"
      contentHTML: "</p>
      
      <p>Dear {{FIRSTNAME}},</p>
      
      <p>First of all, welcome, and thank you for your registration at GEWIS. From tomorrow on, your membership number will be {{LIDNR}}.<br/>
    You can use this membership number to log in to the website, where you can, among other things, subscribe to activities and look at photos from all the fun activities that you, together with the other members, have experienced. 
    Below more information on all the functions of the website can be found, but first of all, you can register to the website using the following link: <a href=\"https://gewis.nl/user/register\">gewis.nl/user/register</a>.</p>
    <p>Besides getting access to the website, you can also create a SudoSOS account, our system with which you will be able to buy drinks from the refrigerators and sweets you can find on the bar.
    You will need this account if you want to get a drink at the weekly social drink (usually called the “borrel”). To do this, first, log in to the GEWIS website using the account created above. After this, go to <a href=\"https://sudosos.gewis.nl\">sudosos.gewis.nl</a>.
    When you log in for the first time, you will have to read and accept the terms and conditions. After that, you can also set a pin code to use the point of sales on your own.</p>
    
    With kind regards,<br/>
    The board of GEWIS"


# If there is more text that goes below the topblock, you can leave it here. Extramessage has one or multiple short messages
    - type: extramessage
      title: ""
      messages:

      # Each extra message has a title and some HTML content. Line-endings halfway are perfectly fine in YAML
      - title: "The GEWIS website"
        contentHTML: "You might have noticed that GEWIS has its own website, but that it might not be as easy to access as you had hoped. Fear not, as this instruction mail should help you in no time! There are several different tabs in which you can find the following information:<br/>
        <ul>
        <li><b>Association</b>: If you have ever wondered who is actively helping the association by means of organizing activities, maintaining the servers, taking pictures, or publishing the association magazine: take a look at this page! All our committees, fraternities, and sororities are listed here. Besides that, you can take a look if you forgot what your board looks like, or how you should sing the GEWIS song ;)</li>
        <li><b>Companies</b>: At some point in the future, you could be looking for an internship or a graduation project from a company. At this header, you find a list of numerous companies offering vacancies for members of GEWIS.</li>
        <li><b>Education</b>: Especially important when the exam weeks are coming near, here you can find all the old exams and summaries that GEWIS has available for the courses of Mathematics and Computer Science. You can also order your books from here, or submit a complaint about a teacher or a course.</li>
        <li><b>Activities</b>: Besides studying, it is of course important to relax and enjoy your student life every once in a while. Here, you find an overview of all the activities GEWIS organizes: from weekends to lunch lectures, from external activities such as a conference to internal activities such as a bridge course. Don’t forget that most activities require you to subscribe in advance and that some activities are full quite fast!</li>
        <li><b>Photos</b>: This kind of speaks for itself: at nearly every activity, members of GEFLITST (the photo committee of GEWIS) are busy taking pictures of our members. If you’re scrolling through the photos, don’t forget to tag the members you know in the picture! This week's photos will be on the website already so check for them regularly :)</li>
        <li><b>Members</b>: In this section, you can find plenty of different important shortcuts to other parts of the website. For example; you can look at an overview of your profile, look up another member if you can’t remember his name, see when the next General Members Meeting (GMM) is, access your SudoSOS account with which you can buy drinks and food (you have to agree to the terms of use before you can buy stuff), and many other shortcuts.
    Be sure to check it out!
    And of course, on our homepage, you can find numerous of these sections in short. A few of the upcoming events, the birthdays of today, the photo of the week, a poll, and of course random infima. So as you can see, there’s a lot to see and do on our website, so be sure to check it out every once in a while!</li>
        </ul>"
      - title: "First-year committees"
        contentHTML: "GEWIS has many committees and fraternities, we even set-up committees dedicated to first-year students every year. As a first year committee you will be experiencing first-hand what being an active GEWIS member is like! Together with your fellow first-year students you will be fleshing out your own identity by creating your very own logo and custom clothing.
    You will also get the opportunity to organize some very fun activities for GEWIS and you can even be a part of workgroups with other first year committee members with whom you will be organizing parties, parent days or even a cantus!
    Furthermore, each semester a scoring competition is held to see which first year committee is the very best of them all.
    Collect points with your committee by passing courses, attending activities and much more!<br/><b>Joining a first-year committee</b>: In the first quartile, an information meeting will be held.  Here, first year committees from previous years will tell you about their fun experiences.
    A second meeting, the formation meeting, will be held to form the first year committees. Not to worry though, it's also possible to join an FYC later in the year.
    We hope to see you at these meetings!>"
      - title: "Ordering books"
        contentHTML: "By becoming a GEWIS member you have the right to a specialized discount! By navigating to <a href=\"https://gewis.nl/books\">gewis.nl/books</a> you can find your study and see which books will be used for your courses."
      - title: "GEWIS on social media"
        contentHTML: "Next to our own photo section on the website, you can also find us on social media. We have Instagram, Facebook, and LinkedIn (see below). Additionally, we have a weekly newsletter, for which you are automatically subscribed. You will get your first newsletter soon!"
        

# You probably want to include this each newsletter
    - type: tinyfooter
      contentHTML: 'You received this email because you registered as a member of GEWIS and your membership was confirmed. This is a one-time mailing to update you about the status of your request.<br/><br/>*If you are paying through SEPA Direct Debit, this approval is pending payment.'

```

### Why is this needed?

Consistency in communication
