### ISSUE TITLE
Graduate renewal

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#285]
### What would you like?

Graduate memberships expire each year; graduates need to be email to renew before that

### Other information

Proposed email:

```yaml
# All mailings require some settings. These can be set here. Don't forget to set the title ("Algemene mededeling; tekst zelf invoeren")
version: 1.1
settings:
    title: "GEWIS Graduate Renewal"
    email: "secretary@gewis.nl"
    #unsubscribe: https://lists.gewis.nl/postorius/lists/gewis.lists.gewis.nl/
    lang: en-UK
    #lang: nl-NL
    #url: "https://secr.personal.gewis.nl/newsletter/2022/preannouncement-GMM-191.html"
    follow: 


# A mailing consists of a series of messageblocks, each with their own type
# The available types are "header", "topblock", "activities", "activityfooter", "extramessage" and "tinyfooter"
messageblocks:

# Each mailing must have a header to make the template shine! It contains the title and the date.
    - type: "header"
      title: "Membership notification"
      date: 2023-05-08

# This is the first block which is shown on top of the message. Recommended for most messages
    - type: topblock
      title: "Expiring membership"
      contentHTML: >
        Dear {{firstname}},<br/><br/>
      
        You are currently registered as a Graduate (<i>Afgestudeerde</i>) at GEWIS until <b>July 1st, 2023</b>. 
        We care about your privacy, so we'd like to confirm that you want to renew this with another year.
        
        <br/><br/>
        Please click <a href='https://database.gewis.nl/'>here</a> to review your personal details and renew 
        your status as graduate of GEWIS for another year.
        If you do not click this link, your status will automatically expire and we will delete your data in 
        the way described in our <a href='https://gewis.nl/association/regulations/privacy-statement'>privacy policy</a>.
        
        <br/><br/>
        If you prefer this, you can also renew your membership by replying to this email.
        Please keep the subject intact so we can process it quicker.
        
        <br/><br/>
        On behalf of the the board,<br/><br/>
        .. ..<br/>
        Secretary of GEWIS ....-....

# If there is more text that goes below the topblock, you can leave it here. Extramessage has one or multiple short messages
    - type: extramessage
      title: ""
      messages:

      # Each extra message has a title and some HTML content. Line-endings halfway are perfectly fine in YAML
      - title: "More information"
        contentHTML: >
          On July 1st, 2021 the new Articles of Association came into effect.        
          This means you can now also be registered with GEWIS as a graduate.
          All non-studying members who were not in an organ were registered as a graduate on aforementioned date. 
          <br/><br/>
          Graduates do not pay contribution and as a graduate, you can still join 
          GEWIS activities or visit the social drink like you used to.
          However, sometimes you have to pay an extra fee to join an (expensive) activity.
          You can also no longer serve on the board of GEWIS or vote during the GMM.
          <br/><br/>
          Article 3.1 of the Internal Regulations allows you to request renewal 
          of your status as graduate. Therefore, you are receiving this email.
          
# You probably want to include this with an announcement
    - type: tinyfooter
      contentHTML: 'You receive this message because your registration as a graduate of GEWIS is almost ending. You can not opt-out of these emails.'
```
